export * from "gatsby-theme-flex/src/blocks";
export { Cover } from "./cover";
export { Offers } from "./offers";
export { Pricing } from "./pricing";
export { RegistrationProcess } from "./registration-process";
export { Contact } from "./contact";
export { Head } from "./head";
export { Schemes } from './schemes';
export { Terms } from './terms';
export { Privacy } from './privacy';
export { Plans } from './plans';
export { About } from './about';
